// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsFMjcwItWKkOS5gMJNUhnX8BXaweKFOk',
    appId: '1:1001568537398:web:5343d49e45023fa60dc197',
    messagingSenderId: '1001568537398',
    projectId: 'supplychain-e8b13',
    authDomain: 'supplychain-e8b13.firebaseapp.com',
    storageBucket: 'supplychain-e8b13.firebasestorage.app',
    measurementId: 'G-5C4CY5ZVCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCLGr4PBSj5cU7WrSYV3sHfJgp1zcau5g',
    appId: '1:1001568537398:android:1c866c7176548d600dc197',
    messagingSenderId: '1001568537398',
    projectId: 'supplychain-e8b13',
    storageBucket: 'supplychain-e8b13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADayUIYPzD-ie3OJ7qu-dzb1gj8Fj9zyk',
    appId: '1:1001568537398:ios:d98e21b6367a93650dc197',
    messagingSenderId: '1001568537398',
    projectId: 'supplychain-e8b13',
    storageBucket: 'supplychain-e8b13.firebasestorage.app',
    iosBundleId: 'com.example.letsSeeWhatHappens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADayUIYPzD-ie3OJ7qu-dzb1gj8Fj9zyk',
    appId: '1:1001568537398:ios:d98e21b6367a93650dc197',
    messagingSenderId: '1001568537398',
    projectId: 'supplychain-e8b13',
    storageBucket: 'supplychain-e8b13.firebasestorage.app',
    iosBundleId: 'com.example.letsSeeWhatHappens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsFMjcwItWKkOS5gMJNUhnX8BXaweKFOk',
    appId: '1:1001568537398:web:6851d0d97efe4a040dc197',
    messagingSenderId: '1001568537398',
    projectId: 'supplychain-e8b13',
    authDomain: 'supplychain-e8b13.firebaseapp.com',
    storageBucket: 'supplychain-e8b13.firebasestorage.app',
    measurementId: 'G-JXQ7YHW9DF',
  );

}