// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGSOU3MJP_IMeQ2r9IkLpvz_JBd4C1vqE',
    appId: '1:931121814619:web:232121da46d2c14e95737e',
    messagingSenderId: '931121814619',
    projectId: 'api-project-b8fec',
    authDomain: 'api-project-b8fec.firebaseapp.com',
    storageBucket: 'api-project-b8fec.firebasestorage.app',
    measurementId: 'G-XR4PN63Z22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQBumRFz5uG3U-YWnAPqoySDWqGLibUhA',
    appId: '1:931121814619:android:832b4c6da707b09b95737e',
    messagingSenderId: '931121814619',
    projectId: 'api-project-b8fec',
    storageBucket: 'api-project-b8fec.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGSOU3MJP_IMeQ2r9IkLpvz_JBd4C1vqE',
    appId: '1:931121814619:web:d05adc25e444c16b95737e',
    messagingSenderId: '931121814619',
    projectId: 'api-project-b8fec',
    authDomain: 'api-project-b8fec.firebaseapp.com',
    storageBucket: 'api-project-b8fec.firebasestorage.app',
    measurementId: 'G-2Y7CM5KQD2',
  );
}
